<?php
/**
 * Implements hook_theme().
 */
function qsi_theme($existing, $type, $theme, $path) {    
    return [
      'qsi' => [
        'variables' => [
          'facebook' => NULL,
          'twitter' => NULL,
          'youtube' => NULL,
          'instagram' => NULL,
          'linkedin' => NULL,
          'icon_size' => NULL
        ],
      ],
    ];
  }

/**
 * Implements hook_preprocess().
 */
function qsi_preprocess_qsi(&$variables) {
  $config = \Drupal::config('qsi.settings'); 
  $variables['facebook'] = $config->get('facebook');
  $variables['twitter'] = $config->get('twitter');
  $variables['youtube'] = $config->get('youtube');
  $variables['instagram'] = $config->get('instagram');
  $variables['linkedin'] = $config->get('linkedin');
  $variables['icon_size'] = $config->get('icon_size');  
}